server:
  port: 8080
  servlet:
    context-path: /
app:
  name: redissonx-server
mybatis:
  mapper-locations: classpath*:config/sqlmap/*/*.xml
  type-aliases-package: com.leshiguang.arch.redissonx.core.entity.gen
threadpool:
  core-pool-size: 10
  max-pool-size: 20
  queue-capacity: 1000
  keep-alive-seconds: 300
dubbo:
  application:
    name: redissonx-server
  metadata-report:
    address: zookeeper://10.19.189.181:2181
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: zookeeper://10.19.189.181:2181
  version: 1.0.0
